apiVersion: apps/v1
kind: Deployment
metadata:
  name:  demo
  namespace: userapp
  labels:
    app:  demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  demo
    spec:
      containers:
      - name:  demo
        image:  94233949/k8s-app:v0.0.2
        ports:
        - containerPort:  3000
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: userapp
spec:
  selector:
    app: demo
  type: ClusterIP
  ports:
  - name: usermgmtui
    protocol: TCP
    port: 3000
    targetPort: 3000
